### ISSUE TITLE
Documentação das Personas do Projeto

### ISSUE THREAD

**Issue by BiancaPatrocinio7** [unb-mds/2023-2-Squad08#11]
# Título: Criação da Documentação das Personas do Projeto

## Descrição:
Estamos buscando melhorar a compreensão das necessidades dos nossos usuários e stakeholders no projeto atual. Uma maneira fundamental de alcançar esse objetivo é criar uma documentação completa das personas envolvidas.

## Tarefas:

- [x] Pesquisa de Usuários: Realizar pesquisa de usuário para identificar as principais personas envolvidas no projeto. Isso inclui entrevistas, análise de dados e feedback de stakeholders.

- [x] Criação de Personas: Com base na pesquisa de usuário, criar personas que representem de forma precisa e completa os diferentes grupos de usuários e stakeholders do projeto.

- [x] Descrição das Personas: Para cada persona, fornecer uma descrição detalhada que inclua informações como nome, cargo, objetivos, desafios, preferências e qualquer outra informação relevante.

- [x] Uso das Personas: Identificar como essas personas serão usadas no projeto, como na tomada de decisões de design, na criação de jornadas do usuário e na definição de requisitos.

- [x] Validação: Validar as personas com a equipe de projeto e os stakeholders para garantir que elas representem com precisão os usuários e partes interessadas envolvidas.

## Critérios de Aceitação:

Documentação completa das personas do projeto.
As personas foram validadas pela equipe de projeto e pelos stakeholders.
As personas estão disponíveis para a equipe de projeto usar em suas atividades.
## Responsáveis:
@cqcoding 

## Data Limite:
18/09/2023

**Comment by cqcoding** [comment]
Aqui está o documento com a descrição das personas para o projeto:  https://docs.google.com/document/d/1m1tk4WAYf5WOwpL6_79ovWvV2Tw_LTMs0wJUyc8OUhM/edit?usp=sharing
