### ISSUE TITLE
Documentação do Código de Conduta da Equipe

### ISSUE THREAD

**Issue by anabborges** [unb-mds/2023-2-Squad08#13]
# Título: Documentação do Código de Conduta da Equipe

## Descrição: 
Estamos buscando criar um Código de Conduta da Equipe transparente. Esta issue destina-se a iniciar o processo de documentação e revisão do nosso Código de Conduta da Equipe para garantir que todos os membros da equipe tenham acesso fácil a diretrizes claras sobre comportamento e expectativas.

## Tarefas propostas:

- [x] Identificar condutas aceitáveis e recomendados na equipe, assim como os não aceitáveis;
- [x] Criar a documentação do Código de Conduta da Equipe;
- [x] Revisar e aprovar o Código de Conduta com os membros da Equipe;

## Critérios de Aceitação:
Documentação completa do Código de Conduta.
Aprovação dos membros.

## Responsáveis:
@VieiraLaris 

## Data Limite:
18/09/2023

**Comment by VieiraLaris** [comment]
O código de conduta do grupo (revisado): https://docs.google.com/document/d/138rHvR2n3hkwwWlL5ZAYR2MaE-w_0a6McITwoZ8pmDE/edit
