### ISSUE TITLE
Capacitação em PyPDF2

### ISSUE THREAD

**Issue by anabborges** [unb-mds/2023-2-Squad08#19]
# Título: Capacitação em PyPDF2 

## Descrição:
Acreditamos que a biblioteca PyPDF2 será de grande importância no desenvolvimento do projeto, ajudando na extração de dados dos PDF's dos diários oficiais. Dessa forma, alguns membros deverão se capacitar nela e compartilhar seus aprendizados.

## Tarefas Propostas:

- [x] **Estudo teórico da biblioteca** - entender o funcionamento da biblioteca, além de analisar se o uso dela é viável para a o projeto;
- [x] **Tentativa de implementação** - fazer o teste com algum PDF para aprender a biblioteca de forma prática;
- [x] **Elaboração de material para estudo e revisão dos membros**;

## Critérios de Aceitação:

- Material sobre a biblioteca PyPDF2;
- Treinamento para os outros membros.

## Responsáveis:
@BiancaPatrocinio7 @matheusbmello 

## Data Limite:
25/09/2023

**Comment by BiancaPatrocinio7** [comment]
Exploramos com entusiasmo a biblioteca PyPDF2 e compartilhamos seu potencial com nossos colegas de trabalho. Essa poderosa ferramenta revelou-se capaz de extrair meticulosamente dados de documentos em formato PDF, convertendo-os com maestria em strings facilmente manipuláveis. Essa funcionalidade inovadora simplifica significativamente o processo de criação de arquivos de texto, proporcionando uma experiência mais eficiente e versátil para a gestão de informações.
