### ISSUE TITLE
Protótipo: Funcionalidade

### ISSUE THREAD

**Issue by bdebatata** [unb-mds/2023-2-Squad08#21]
# Descrição

Na fase de prototipação, delineamos duas abordagens distintas: Design e Funcionalidade. A parcela de Funcionalidade ficará responsável por conceber as funcionalidades que o usuário deverá ter no site, assim como sua interação com os dados.

# Objetivos: 

- [x] Conceber como será a interação do usuário com os dashboards
- [x]  Conceber como será a disposição dos dados

# Responsáveis:

- @anabborges 
- @vitorfleonardo 

# Critérios de avaliação:

- Protótipo no Figma para avaliação da equipe

**Comment by vitorfleonardo** [comment]
Para essa issue, utilizamos o protótipo de baixa fidelidade (elaborado na sprint 02) para assim construirmos um novo protótipo, dessa vez de alta fidelidade. Nesse sentido, definimos conteúdos para cada página de nosso site, de acordo com o storymap.

**Comment by anabborges** [comment]
[link para o protótipo](https://www.figma.com/file/1JtfmfvGR7FGMYcPoCWa6Z/M%C3%A9dia-fidelidade?type=design&node-id=0-1&mode=design&t=hN7B9mbNdySOxk3J-0)
