### ISSUE TITLE
Implementação Inicial: PyPDF2

### ISSUE THREAD

**Issue by bdebatata** [unb-mds/2023-2-Squad08#23]
# Descrição:

Como estudado na sprint anterior, a ferramente PyPDF2 é uma ferramenta extremamente útil para a extração de texto de PDF. Portanto se mostra necessária para a implementação do projeto. 

# Objetivos:

- [x] Implementar o extrator de texto dos PDF's 
- [x] Testes de leitura de PDF's alocados em uma pasta do projeto 
- [x] Testes de criação dos .txt em uma pasta do projeto
- [x] Nomeação dos arquivos .txt com as datas de sua publicação

# Responsáveis
- @BiancaPatrocinio7 
- @matheusbmello 

# Critérios de Avaliação 
- O bot precisa extrair o texto e salvar em .txt de forma automática

**Comment by BiancaPatrocinio7** [comment]
A implementação inicial do PyPDF foi realizada, se encontra dentro da pasta de estudos.
