### ISSUE TITLE
Documentação: Story Map

### ISSUE THREAD

**Issue by bdebatata** [unb-mds/2023-2-Squad08#24]
# Descrição 

A técnica da Story Map se fundamenta na organização dos requisitos com foco na jornada do usuário, apresentando uma vantagem significativa ao agrupar as histórias em Épicos, o que torna mais fácil a compreensão de como se relacionam com a jornada do usuário. Além disso, o Story Map pode desempenhar um papel crucial na estruturação das entregas (releases) de um produto. Portanto parte da equipe assuma a responsabilidade de criar um Story Map que conecte os requisitos identificados com as personas.

# Objetivos

- [x] Relacionar os requisitos e as personas identificadas.
- [x] Documentar a Story Map.

# Responsáveis
A equipe irá realizar uma reunião para discussão do problema e então sua documentação.

# Critérios de Avaliação 
- Os requisitos devem estar relacionados com as personas de forma lógica e concisa.

**Comment by vitorfleonardo** [comment]
Foi realizada uma reunião em grupo para elaboração de histórias de usuários e todas essas histórias criadas estão documentadas propriamente.
