### ISSUE TITLE
Treinamento da metodologia SCRUM

### ISSUE THREAD

**Issue by BiancaPatrocinio7** [unb-mds/2023-2-Squad08#3]
# Tema: Responsabilidades/posições segunda a metodologia SCRUM e como funciona
 Data da treinamento: 05 e 07 de setembro de 2023 (quinta-feira)
Horário: a definir
<div align="left">

Participantes: 
- Bruno Henrique Duarte (Coelho)
- Cecília Ernesto Silva Quaresma (Coelha)
- Bianca Patrocínio Castro 
- Larissa de Jesus Vieira 
- Ana Clara Barbosa Borges
- Vitor Feijó Leonardo

**Comment by cqcoding** [comment]
O treinamento foi curto, mas esclareceu alguns pontos chave sobre a metodologia, criei um arquivo com os conceitos mais relevantes sobre o SCRUM para explicar ao grupo: [https://docs.google.com/document/d/1GePbD2VlDXiNYzD9927TP7a_gG2RII6czieGVYWj_Jk/edit?usp=sharing](url)

**Comment by bdebatata** [comment]
O livro que utilizei como referência para a o treinamento foi: https://portaldaobmep.impa.br/uploads/material_teorico/d9gycv8klfcwc.pdf

Os slides do treinamento ficaram bem curtos para que ficasse mais resumido e útil possível: https://www.canva.com/design/DAFtnCaE_ZE/d3CtEeVEfoST9tfKBFrh2w/edit?utm_content=DAFtnCaE_ZE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
