### ISSUE TITLE
Mudança no protótipo de alta fidelidade

### ISSUE THREAD

**Issue by vitorfleonardo** [unb-mds/2023-2-Squad08#31]
# Descrição 
Será incluíde uma nova página no protótipo e essa nova página terá uma análise de  dados de anomalias, tais como trocas de nomeações e exonerações. 
# Objetivos
- [x] Criar nova página no protótipo 
- [x] Criar uma forma de análise desses dados 
- [x] Fazer o design 
# Responsáveis
@VieiraLaris 
# Critérios de avaliação
* Uma página com uma análise de anomalias nos diários que seja visivelmente interessante

**Comment by VieiraLaris** [comment]
Foi criada mais uma página no protótipo de alta fidelidade chamada "Anomalias", onde o usuário poderá pesquisar por um município e encontrar atividades incomuns relacionadas a nomeações e exonerações.
Link do protótipo no Figma: https://www.figma.com/file/1JtfmfvGR7FGMYcPoCWa6Z/M%C3%A9dia-fidelidade?type=design&node-id=0-1&mode=design&t=Y1PqPO1YY482gDEK-0
