### ISSUE TITLE
Desenvolver Menu bar lateral

### ISSUE THREAD

**Issue by vitorfleonardo** [unb-mds/2023-2-Squad08#34]
# Descrição
Utilizando ReactJS, criar o componente menu bar do protótipo de alta fidelidade. 
# Objetivos
- [x] Criar o menu bar lateral
# Responsáveis
@anabborges 
@cqcoding 
@VieiraLaris 
@vitorfleonardo 
# Critérios de avaliação 
* Desenvolver o menu bar fixo na lateral esquerda de a cordo com o protótipo

**Comment by anabborges** [comment]
Foi desenvolvido o componente menuBar na nossa branch front-end, onde conseguimos navegar entre as páginas do projeto
