### ISSUE TITLE
Dashboards no front-end

### ISSUE THREAD

**Issue by vitorfleonardo** [unb-mds/2023-2-Squad08#38]
# Descrição
Introduzir dashboards ao front-end, conforme o protótipo de alta fidelidade. 

# Objetivos
- [x] Pesquisar por bibliotecas úteis para a issue
- [x] Checar utilidade das bibliotecas usadas pela exoonero: nextJS, Tywind e Apex Charts
- [x] Incrementar um exemplo visível ao front-end
# Responsáveis
@anabborges 
@VieiraLaris 
# Critérios de avaliação 
* Ter as dashboards implementadas no front-end

**Comment by VieiraLaris** [comment]
A implementação dos Dashboards na página Home foi iniciada nessa issue. Foram inseridos 2 gráficos, que ainda precisam ser configurados, e a biblioteca utilizada foi o ApexCharts. Outros elementos e funcionalidades precisam ser adicionados, dessa forma a finalização ocorrerá em outra issue.
