### ISSUE TITLE
Implementação Regex

### ISSUE THREAD

**Issue by vitorfleonardo** [unb-mds/2023-2-Squad08#39]
# Descrição
Minerar dados do .txt gerado pelo PyPDF, para análise.
# Objetivos
- [x] Criar algoritmo 
# Responsáveis
@bdebatata 
@BiancaPatrocinio7 
# Critérios de avaliação 
* IMplementar código capaz de identificar cadeias de caracteres de interesse.

**Comment by bdebatata** [comment]
O código commitado na implementação foi a implementação inicial do Regex, porém contém bugs a serem resolvidos.
