### ISSUE TITLE
Treinamento da plataforma Miro

### ISSUE THREAD

**Issue by BiancaPatrocinio7** [unb-mds/2023-2-Squad08#4]
# Tema: Gerenciamento de Projetos 
 Data da treinamento: 07de setembro de 2023 (quinta-feira)
Horário: a definir
<div align="left">

Participantes: 
- Ana Clara Barbosa Borges (Coelha)
- Bianca Patrocínio Castro 
- Larissa de Jesus Vieira 
- Bruno Henrique Duarte
- Cecília Ernesto Silva Quaresma
- Vitor Feijó Leonardo
- Matheus de Mello Barbosa

**Comment by anabborges** [comment]
### Treinamento realizado
[Material para estudo](https://docs.google.com/document/d/1MCqzqqpjlSEsY2g-Z0QiDcpM6UXeIWXUPYLZagJaoNU/edit?usp=sharing)
