### ISSUE TITLE
Encadeamento de processos da camada de dados

### ISSUE THREAD

**Issue by vitorfleonardo** [unb-mds/2023-2-Squad08#40]
# Descrição
Adicionar o PyPDF2 ao código de WebScraper para extração dos .txt e exclusão dos PDF's, em tempo de execução.
# Objetivos
- [x] Adaptar o código do PyPDF ao código de Webscraper
- [x] Adicionar código para exclusão do PDF após execução do PyPDF
- [x] Testar 
# Responsáveis
@bdebatata 
@BiancaPatrocinio7 
@cqcoding 
# Critérios de avaliação 
* Código conseguir utilizar um PDF em tempo de execução, extraindo as informações necessárias.

**Comment by BiancaPatrocinio7** [comment]
Nosso código anterior conseguia buscar os arquivos PDF, baixá-los, extrair o texto e remover os PDFs, porém isso resultava no acúmulo de arquivos desnecessários no computador. Na resolução dessa questão, implementamos melhorias em nosso projeto, otimizando o encadeamento desses processos. Agora, todas as etapas ocorrem de forma integrada durante o tempo de processamento, proporcionando uma execução mais eficiente e evitando a poluição desnecessária do sistema com arquivos temporários.
