### ISSUE TITLE
Treinamento Front-end

### ISSUE THREAD

**Issue by cqcoding** [unb-mds/2023-2-Squad08#54]
# Descrição
O objetivo dessa issue é explicar a cada membro do grupo os avanços do front-end, para integrar melhor o projeto.
# Objetivos
- [x] Revisar o front-end
- [x] Agendar uma reunião para explicar ao grupo
# Responsáveis
@anabborges @VieiraLaris

**Comment by anabborges** [comment]
Treinamento realizado com o grupo no dia 02/11
