### ISSUE TITLE
Treinamento Regex

### ISSUE THREAD

**Issue by cqcoding** [unb-mds/2023-2-Squad08#55]
# Descrição
O intuito dessa sprint é explicar o funcionamento do back-end, a parte da extração e mineração dos dados
# Objetivos
- [x] Revisar o Regex
- [x] Agendar uma reunião para explicar ao grupo
# Responsáveis
@bdebatata @BiancaPatrocinio7

**Comment by bdebatata** [comment]
Durante uma reunião do dia 02/11 foi feita uma reunião com os membros para que todos estejam a par do processo que está sendo realizado e como está sendo realizado.
