### ISSUE TITLE
Buscar padrões para o Regex

### ISSUE THREAD

**Issue by cqcoding** [unb-mds/2023-2-Squad08#57]
# Descrição
Achar uma solução para o problema da padronização dos diários oficiais e implementar no regex.
# Objetivos
- [ ] Entender como cada diário padroniza nomeações e exonerações

# Responsáveis
@bdebatata @BiancaPatrocinio7 @cqcoding

**Comment by BiancaPatrocinio7** [comment]
Criamos uma estrutura para o Regex pegar os dados de 2009 a partir do nome dos Municípios, conseguido avaliar bem esse ano.
