### ISSUE TITLE
Treinamento Metodologia XP

### ISSUE THREAD

**Issue by cqcoding** [unb-mds/2023-2-Squad08#58]
# Descrição
Entender o método extreme programming que será utilizado na segunda etapa do projeto
# Objetivos
- [ ] Agendar uma reunião para explicar ao grupo
- [ ] Pesquisar sobre o metodo XP
# Responsáveis
@vitorfleonardo @cqcoding

**Comment by vitorfleonardo** [comment]
Treinamento apresentado no dia 02/11/2023 ás 10:20! Link do slide da apresentação: https://docs.google.com/presentation/d/14eY_cUCBBfTpQinccfVvfnHpiDtQxE-H3WjVS5kFHaI/edit?usp=sharing

**Comment by vitorfleonardo** [comment]
Feito
