### ISSUE TITLE
Treinamento do Querido Diário

### ISSUE THREAD

**Issue by BiancaPatrocinio7** [unb-mds/2023-2-Squad08#6]
# Tema: O que é o projeto Querido diário?
 Data da treinamento: 07de setembro de 2023 (quinta-feira)
Horário: a definir
<div align="left">

Participantes: 
- Larissa de Jesus Vieira (Coelha)
- Bianca Patrocínio Castro 
- Bruno Henrique Duarte
- Cecília Ernesto Silva Quaresma
- Ana Clara Barbosa Borges
- Vitor Feijó Leonardo

**Comment by VieiraLaris** [comment]
Material utilizado:
https://docs.google.com/document/d/1vTakynRdNQz5Wqpc7I1HoSKc4gpdyKBuUsQw5vOVTD4/edit
