### ISSUE TITLE
Bibliotecas para Processamento de Linguagem Natural (NLP)

### ISSUE THREAD

**Issue by BiancaPatrocinio7** [unb-mds/2023-2-Squad08#68]
# Descrição
O propósito desta issue é aprofundar o estudo em Processamento de Linguagem Natural (NLP) e aplicá-lo na tarefa de buscar os nomes das pessoas que foram exoneradas e nomeadas nos Diários Oficiais do Rio Grande do Sul.

# Objetivos
- [ ] Compreender os Fundamentos
- [ ] Desenvolver Habilidades em Programação e Bibliotecas
- [ ] Aplicar NLP em nosso projeto
# Responsáveis
@cqcoding @VieiraLaris @vitorfleonardo 
# Critérios de avaliação 
- [ ] Garantir a qualidade dos nomes extraídos

**Comment by vitorfleonardo** [comment]
FIzemos a primeira implementação do Word2vac com proposito de testar o algoritmo para coleta de nomes, cargos e palvras similares. O Word2Vec é uma ferramenta de processamento de linguagem que converte palavras em números, capturando conexões de significado com base no contexto. Estamos confiantes do resultado.
