### ISSUE TITLE
Treinamento sobre Parser (Duo)

### ISSUE THREAD

**Issue by bdebatata** [unb-mds/2023-2-Squad08#7]
# Tema: Parser
 Participantes:
- Ana Clara Barbosa Borges (Coelha)
- Bianca Patrocínio Castro (Coelha)
- Bruno Henrique Duarte
- Cecília Ernesto Silva Quaresma
- Larissa de Jesus Vieira
- Vitor Feijó Leonardo
- Matheus de Mello Barbosa

 Objetivos: 

- [ ] Trazer um treinamento sobre Parser.
- [ ] Trazer materiais/vídeos/livros que possam acrescentar no estudo. 
- [ ] Trazer exemplos de código de como os Parsers funcionam

**Comment by BiancaPatrocinio7** [comment]
# Parser
- Analisador sintático ou parser é um objeto que faz análise sintática de um texto para determinar a sua estrutura lógica.
- Definição técnica utilizada por programadores. Significa extrair conteúdos de um conjunto de caracteres (geralmente separados por ponto e virgula, pipe, chave ou colchete). Parsear ou parseamento, é muito utilizado em estruturas de texto JSON, CSV e XML.
## Como criar um parser em Python?

É possível fazer isso usando puro Python, sem importar nenhum módulo. Basicamente é um exercício de manipulação de string's. Certamente que há formas mais eficientes de fazer o mesmo, como por exemplo, usando o referido re (módulo que lida com regex, [regular expressions](https://pt.wikipedia.org/wiki/Express%C3%A3o_regular)).
Continuando com o puro Python, os passos gerais são:
### Identificar o formato do ficheiro
- O que separa o parâmetro do valor?
- Comentários
- Grupos
- Casos particulares
### Definir uma estrutura de dados onde guardar a informação (exemplo)
- Criar um dicionário em que cada chave é um parâmetro, que guarda um valor
- Quantos níveis são precisos? Preciso de um dicionário de dicionários?
- A ordem é importante? Os dicionários não são ordenados. Em alternativa, pode-se usar um [OrderedDict](https://docs.python.org/3.5/library/collections.html#collections.OrderedDict).
### Escrever ficheiro ou converter
- É necessário escrever o ficheiro de volta?
- Em que formato? Igual ou diferente? (neste caso pretende-se XML)

### Vamos a isso.
1. Identificar o formato do ficheiro
Vendo o [ficheiro de exemplo](http://pastebin.com/404dp2Ny), identificamos o seguinte:
comentários começam por #
grupos acabam em :
parâmetros e valores estão separados por =
há parâmetros sem grupo, que aparecem primeiro
assumimos que todos os parâmetros seguintes pertencem a algum grupo
Atenção: na linha 59 há um comentário que não está identificado: Game Label Image; eu coloquei um #, mas é possível lidar com estas situações no código

2. Definir uma estrutura de dados onde guardar a informação
Como temos parâmetros separados por grupos, neste exemplo decidi por uma estrutura do tipo dicionário de dicionários. Exemplo
cfg = {
    'grupo 1': {
        'param1': 1,
        'param2': 'abc'
    },
    'grupo 2': {
        'paramA': 'foo',
        'paramB': 123
    }
}

Um dos grupos vai ser o 'geral', que contém os parâmetros que surgem primeiro, fora de qualquer grupo.

3. Escrever ficheiro ou converter
Não vou cobrir esta parte na minha resposta, já que o pretendido é converter para XML, e isso já foge à pergunta principal (como criar o parser). Aconselho a leitura do seguinte tópico: [XML to/from a Python dictionary](https://stackoverflow.com/questions/3292973/xml-to-from-a-python-dictionary).
