### ISSUE TITLE
Implementação do Word2Vec

### ISSUE THREAD

**Issue by anabborges** [unb-mds/2023-2-Squad08#79]
# Descrição
Após estudos e testes com o Word2Vec, decidimos prosseguir com ele a fim de coletarmos os nomes das pessoas exoneradas e nomeadas.
# Objetivos
- [x] Implementar o Word2Vec para os anos 2009, 2013, 2017, 2020 e 2021
# Responsáveis
@cqcoding @VieiraLaris @vitorfleonardo 
# Critérios de avaliação 
* Coletar os nomes das pessoas exoneradas e nomeadas nos anos determinados
* Garantir que os nome coletados são os corretos

**Comment by cqcoding** [comment]
O word2vez foi utilizado como ampla base para extrair boa parte dos nomes de 2017, alguns refinamentos forma feitos de forma manual para aproveitar os resultados de forma direta no front-end.
