### ISSUE TITLE
Criação dos testes unitários

### ISSUE THREAD

**Issue by anabborges** [unb-mds/2023-2-Squad08#80]
# Descrição
Deverão ser feitos os testes unitários e automatizados com a pytest
# Objetivos
- [x] Criação de testes unitários
- [ ] Automatização dos testes
# Responsáveis
@BiancaPatrocinio7 @bdebatata 
# Critérios de avaliação 
* Testes implementados

**Comment by bdebatata** [comment]
Criação dos testes unitários da camada de dados, ao final todos os testes passaram e cumpriram o que era esperado.
