### ISSUE TITLE
Refatoração da Camada de Dados

### ISSUE THREAD

**Issue by BrunoHDuarte2** [unb-mds/2023-2-Squad08#85]
# Descrição
Adequação do código aos padrões do PyLint
# Objetivos
- [x] Alterar o código para que se adeque a análise do PyLint 
# Responsáveis
@bdebatata 
# Critérios de avaliação 
Não ocorrer erros na análise feita no Pipeline

**Comment by bdebatata** [comment]
Ocorreram alguns erros no que tange a adequação do código, ao cria um código .pylintrc era possível remover alguns erros que queria se ignorar, porém quando o código ia para o pipeline ele não usava desse arquivo, após desabilitar alguns erros dentro de cada arquivo o código passou.
