### ISSUE TITLE
Implementar rank de municípios 

### ISSUE THREAD

**Issue by vitorfleonardo** [unb-mds/2023-2-Squad08#86]
# Descrição
Fazer os dois ranks de municipios que mais nomeiam e exoneram funcionais.
# Objetivos
- [x] Fazer somatório por município na camada de dados
- [x] Implementar o rank com as informações da camada de dados
# Responsáveis
@BiancaPatrocinio7 
@anabborges 
@matheusbmello

**Comment by BiancaPatrocinio7** [comment]
Atualizamos os dados usando o código de extrair, facilitando para o cálculo da soma das exonerações e nomeações dos municípios. Implementamos na tela Home com os dados o Rank.
