### ISSUE TITLE
Treinamento de Empacotamento de Dados (Duo)

### ISSUE THREAD

**Issue by bdebatata** [unb-mds/2023-2-Squad08#9]
# Tema: Empacotamento de Dados em Python
Participantes:

- Cecília Ernesto Silva Quaresma (Coelha)
- Larissa de Jesus Vieira (Coelha)
- Ana Clara Barbosa Borges 
- Bianca Patrocínio Castro 
- Bruno Henrique Duarte
- Vitor Feijó Leonardo
- Matheus de Mello Barbosa

Objetivos: 

- [x] Trazer ao grupo um treinamento sobre Empacotamento de Dados em Python.
- [x] Trazer materiais de apoio ao estudo.
- [x] Trazer exemplos de como esse processo é feito.

**Comment by VieiraLaris** [comment]
Tutorial ótimo sobre como empacotar um projeto em Pyhton e como disponibilizá-lo no PyPi: https://youtu.be/_14MS9oFZZI?si=iujfw2Pktuyk3twY
Material de apoio do tutorial: https://doc.clickup.com/36904728/d/h/1367rr-543/246df89507b2ab3

**Comment by VieiraLaris** [comment]
Material utilizado para o treinamento: https://docs.google.com/document/d/10TYz-1A54K9JEOMQ1UTPoh72gKIUh5z0bP49gnbUGB4/edit
